name = "ElasticMatrixFactorizations"
uuid = "d7e164e0-cbf3-40c8-8f3e-ab4b12bf7797"
authors = ["Cameron Ibrahim <dev@cameronibrahim.com>"]
version = "0.1.0"

[deps]
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
